name: ariel-2025
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyarrow
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - jupyter
  - ipykernel
  - pytorch
  - pip
